### PR TITLE
NOTICK: Update the Gradle project structure.

### PR DESCRIPTION
**Pull request by chrisr3**
I haven't modified the plugin itself here; only the Gradle project that builds it. So to that end:

- This plugin is written in Java, not Groovy, so stop applying the `groovy` plugin.
- Add `pluginManagement` block to `settings.gradle`.
- Update versions of Gradle Publish and Artifactory plugins.
- Use Gradle's "task configuration avoidance" wherever possible.
- Add `gradle.properties` file.
- _And as for `buildSrc`....!??!_

I am _assuming_ that whatever is happening in the `buildSrc` is a substitute for using `org.gradle.testkit.runner.GradleRunner`. However, I _*strongly*_ recommend using the `GradleRunner` instead, not least because you are currently duplicating your plugin's dependencies in a non-obvious and unmaintainable way.

### CODE REVIEW

**Comment by Schife** [comment]
The build source was a funky hack i cooked up in order to apply the plugin on itself so we can do an actual integration test

**Comment by chrisr3** [comment]
> The buildSrc was a funky hack i cooked up in order to apply the plugin on itself so we can do an actual integration test

Happily, I am familiar with `GradleRunner`... :wink:

**Comment by Schife** [comment]
Looks like the changes are breaking the PR build since no tests are being discovered anymore

**Comment by Schife** [comment]
The tests are under a groovy folder so easy fix

**Comment by chrisr3** [comment]
> The tests are under a groovy folder so easy fix

Heh, despite this plugin not containing a single file written in Groovy? :grinning:

**Comment by Schife** [comment]
Initially the plugin was written in groovy but the files were transitioned to Java one at a time

**Pull request merged**
